# Test helpers: fixture loading and the assertion macros the suite is built on.

using Test
using JSON3

const FIXTURE_DIR = joinpath(@__DIR__, "fixtures")
const MANIFEST_PATH = joinpath(FIXTURE_DIR, "manifest.json")

"""
    fixture(name) -> NamedTuple

Load the reference arrays for case `name` from `test/fixtures/`.

Fixtures are generated by `tools/python_ref/gen_fixtures.py` against a pinned
OpenCV/NumPy environment and committed, so the test suite runs on a bare clone
with no Python present. See `tools/python_ref/README.md` to regenerate.

Each fixture is a directory holding one `.bin` per array plus a `meta.json`
describing shapes, element types, and the parameters the case was generated
with. A flat binary format is used rather than `.npz` so that loading needs no
Python-format reader.
"""
function fixture(name::AbstractString)
    dir = joinpath(FIXTURE_DIR, name)
    isdir(dir) || throw(ArgumentError(
        "fixture \"$name\" not found at $dir. Run " *
        "`julia --project=. tools/python_ref/gen_fixtures.jl` or see " *
        "tools/python_ref/README.md."))
    meta = JSON3.read(read(joinpath(dir, "meta.json"), String))
    arrays = Dict{Symbol,Any}()
    for (key, spec) in pairs(meta.arrays)
        T = _fixture_eltype(String(spec.dtype))
        dims = Tuple(Int.(spec.shape))
        raw = read(joinpath(dir, String(key) * ".bin"))
        expected = prod(dims) * sizeof(T)
        length(raw) == expected || error(
            "fixture $name/$key: expected $expected bytes for " *
            "$dims $T, got $(length(raw))")
        # Python writes C-order (row-major); reading into the reversed shape and
        # permuting gives the same logical array in Julia's column-major layout.
        arrays[Symbol(key)] = permutedims(reshape(reinterpret(T, raw), reverse(dims)),
                                          ndims_perm(length(dims)))
    end
    return (; arrays = NamedTuple(arrays), params = meta.params)
end

ndims_perm(n::Int) = ntuple(i -> n - i + 1, n)

function _fixture_eltype(s::AbstractString)
    T = get(FIXTURE_DTYPES, s, nothing)
    isnothing(T) && throw(ArgumentError("unsupported fixture dtype \"$s\""))
    return T
end

const FIXTURE_DTYPES = Dict{String,DataType}(
    "uint8" => UInt8, "int8" => Int8,
    "uint16" => UInt16, "int16" => Int16,
    "uint32" => UInt32, "int32" => Int32,
    "uint64" => UInt64, "int64" => Int64,
    "float32" => Float32, "float64" => Float64,
    "complex64" => ComplexF32, "complex128" => ComplexF64,
    "bool" => Bool,
)

"""
    has_fixtures() -> Bool

Whether the fixture corpus is present. Tests that compare against OpenCV are
skipped when it is not, so a bare clone still runs the truth-based suite.
"""
has_fixtures() = isfile(MANIFEST_PATH)

# ---------------------------------------------------------------------------
# Assertion macros
# ---------------------------------------------------------------------------

"""
    @test_identical a b

Assert two arrays are bit-for-bit identical, including `NaN` payloads and the
sign of zero.

`isequal` already treats `NaN === NaN` and distinguishes `-0.0` from `0.0`, but
elementwise `==` does not, and `≈` hides exactly the class of error this suite
exists to catch. Used wherever a computation is expected to reproduce a
reference exactly.
"""
macro test_identical(a, b)
    quote
        local x, y = $(esc(a)), $(esc(b))
        @test size(x) == size(y)
        @test all(isequal.(x, y))
    end
end

"""
    @test_approx a b atol rtol

Assert two arrays agree to a tolerance, treating `NaN` as equal to `NaN` so that
masked-out pixels compare cleanly. Reports the worst offending index on failure,
which a bare `≈` does not.
"""
macro test_approx(a, b, atol = 1e-6, rtol = 1e-6)
    quote
        local x, y = $(esc(a)), $(esc(b))
        local at, rt = $(esc(atol)), $(esc(rtol))
        @test size(x) == size(y)
        local worst_i, worst_d = nothing, 0.0
        for i in eachindex(x, y)
            (isnan(x[i]) && isnan(y[i])) && continue
            local d = abs(float(x[i]) - float(y[i]))
            local tol = at + rt * max(abs(float(x[i])), abs(float(y[i])))
            if d > tol && d > worst_d
                worst_i, worst_d = i, d
            end
        end
        if isnothing(worst_i)
            @test true
        else
            @test worst_d == 0.0 || error(
                "arrays differ at index $worst_i: $(x[worst_i]) vs " *
                "$(y[worst_i]) (Δ = $worst_d, atol = $at, rtol = $rt)")
        end
    end
end

"""
    @test_divergence a b max_fraction

Assert that at most `max_fraction` of elements differ between two arrays.

The correctness gate for comparisons where exact agreement is not expected
*and not wanted* — this package deliberately fixes several defects in the Python
reference, so a handful of pixels legitimately choose a different correlation
peak. Rather than loosening the assertion to meaninglessness, the fraction that
differs is bounded and tracked: a regression shows up as the count rising.

`NaN` in the same position in both arrays counts as agreement.
"""
macro test_divergence(a, b, max_fraction)
    quote
        local x, y = $(esc(a)), $(esc(b))
        local maxfrac = $(esc(max_fraction))
        @test size(x) == size(y)
        local ndiff = 0
        for i in eachindex(x, y)
            isequal(x[i], y[i]) && continue
            (isnan(x[i]) && isnan(y[i])) && continue
            ndiff += 1
        end
        local frac = ndiff / length(x)
        if frac > maxfrac
            error("$ndiff of $(length(x)) elements differ ($(round(100frac, digits=3))%), " *
                  "budget is $(round(100maxfrac, digits=3))%")
        end
        @test frac <= maxfrac
    end
end

# ---------------------------------------------------------------------------
# Synthetic test data
# ---------------------------------------------------------------------------

"""
    synthetic_texture(sz; seed = 0, T = Float32) -> Matrix{T}

A band-limited random texture suitable for correlation tests.

White noise is a poor test input: it correlates only at exactly zero lag, so a
peak is found but nothing is learned about the shape of the correlation surface
or about subpixel behaviour. Smoothing the noise produces a surface with a
finite-width peak, which is both more realistic and a stricter test.
"""
function synthetic_texture(sz::Tuple{Int,Int}; seed::Integer = 0, T::Type = Float32)
    rng = Random.MersenneTwister(seed)
    a = randn(rng, Float64, sz)
    # Three passes of a 3x3 box blur approximate a Gaussian well enough, and
    # keep this helper dependency-free.
    for _ in 1:3
        a = _box3(a)
    end
    a .-= minimum(a)
    m = maximum(a)
    m > 0 && (a ./= m)
    return T <: Integer ? round.(T, a .* typemax(T)) : T.(a)
end

synthetic_texture(n::Integer; kw...) = synthetic_texture((Int(n), Int(n)); kw...)

"""
    rotate_bilinear(img, deg) -> Matrix{Float32}

`img` rotated `deg` degrees about its own centre, by bilinear resampling, with out-of-image samples
zero.

A test helper for the rotation search, and bilinear rather than nearest-neighbour deliberately:
`AutoRIFT._rotate_chip` is bilinear, so a nearest-neighbour scene would make every measurement of the
search a measurement of the *mismatch* between two resamplers. Same sign convention and same
half-pixel centre as `_rotate_chip`, for the same reason.

**Deliberately not a call to `_rotate_chip`, which it near-duplicates.** The test this exists for
asserts that counter-rotating a chip with `_rotate_chip` recovers correlation against an
independently rotated scene. Generating the scene with the same function would let a broken rotator
cancel against itself and the assertion pass regardless — the duplication is what keeps the two
sides independent. (It would also need a full-image `CorrelationWorkspace` and its FFT buffers,
which is beside the point.)
"""
function rotate_bilinear(img::AbstractMatrix, deg::Real)
    nr, nc = size(img)
    yc, xc = (nr + 1) / 2, (nc + 1) / 2
    s, c = sincos(deg2rad(Float64(deg)))
    out = zeros(Float32, nr, nc)
    @inbounds for j in 1:nc, i in 1:nr
        dy, dx = i - yc, j - xc
        sy = yc + c * dy + s * dx
        sx = xc - s * dy + c * dx
        i0, j0 = floor(Int, sy), floor(Int, sx)
        (i0 < 1 || j0 < 1 || i0 + 1 > nr || j0 + 1 > nc) && continue
        fy, fx = sy - i0, sx - j0
        out[i, j] = (1 - fy) * ((1 - fx) * img[i0, j0] + fx * img[i0, j0 + 1]) +
                    fy * ((1 - fx) * img[i0 + 1, j0] + fx * img[i0 + 1, j0 + 1])
    end
    return out
end

function _box3(a::Matrix{Float64})
    out = similar(a)
    nr, nc = size(a)
    @inbounds for j in 1:nc, i in 1:nr
        s, n = 0.0, 0
        for dj in -1:1, di in -1:1
            ii, jj = i + di, j + dj
            if 1 <= ii <= nr && 1 <= jj <= nc
                s += a[ii, jj]
                n += 1
            end
        end
        out[i, j] = s / n
    end
    return out
end

"""
    shifted_pair(sz, shift; seed = 0, T = Float32) -> (reference, secondary)

A synthetic image pair where `secondary` is `reference` displaced by
`shift = (dx, dy)` pixels. Integer shifts are exact; fractional shifts are
produced by bilinear interpolation.

This is the package's primary correctness oracle: unlike a comparison against
the Python reference, the answer here is known exactly rather than merely
agreed upon.
"""
function shifted_pair(sz::Tuple{Int,Int}, shift::Tuple{Real,Real};
                      seed::Integer = 0, T::Type = Float32)
    # Generate oversized so that shifting does not pull in out-of-bounds data,
    # which would otherwise put an artificial edge inside the search window.
    pad = ceil(Int, maximum(abs, shift)) + 2
    big = synthetic_texture((sz[1] + 2pad, sz[2] + 2pad); seed, T = Float64)
    ref = big[(pad + 1):(pad + sz[1]), (pad + 1):(pad + sz[2])]
    sec = _shift_bilinear(big, shift)[(pad + 1):(pad + sz[1]), (pad + 1):(pad + sz[2])]
    conv = T <: Integer ? x -> round(T, clamp(x, 0, 1) * typemax(T)) : x -> T(x)
    return conv.(ref), conv.(sec)
end

shifted_pair(n::Integer, shift; kw...) = shifted_pair((Int(n), Int(n)), shift; kw...)

"""
    chip_and_window(img, centre, chip_size, radius; shift = (0, 0), window_from = img)
        -> (chip, window)

A chip and its search window, cut about `centre = (row, col)` in the layout `correlate!` requires.

The window extent is the delicate part, and it was written out by hand at seven call sites before
this helper existed — in three spellings of the same arithmetic (`+ h + r - 2` and `+ h - 2 + r`
differ textually but not numerically, so grep did not connect them). `correlate!`'s window is
**deliberately asymmetric**: it reaches `radius` one way and `radius - 1` the other, so the surface
is an even `2 * radius` and zero displacement lands on a sample rather than between two. Get the
`-2` wrong and the correlator throws a `DimensionMismatch` that reads as a test bug rather than a
convention error.

`shift` offsets the *chip* only, which is how a known displacement is set up: the window stays put
and the chip is cut from `shift` pixels away, so the peak must land at `shift`.

`window_from` cuts the window from a different image than the chip — the reference/secondary split
that a real pair has.
"""
function chip_and_window(img::AbstractMatrix, centre::Tuple{Integer,Integer},
                         chip_size::Integer, radius::Integer;
                         shift::Tuple{Integer,Integer} = (0, 0),
                         window_from::AbstractMatrix = img)
    cy, cx = centre
    sy, sx = shift
    h = chip_size ÷ 2
    chip = img[(cy - h + sy):(cy + h - 1 + sy), (cx - h + sx):(cx + h - 1 + sx)]
    window = window_from[(cy - h - radius):(cy + h + radius - 2),
                         (cx - h - radius):(cx + h + radius - 2)]
    return chip, window
end

# Sample `a` at (i - dy, j - dx) so the result is `a` translated by (+dx, +dy).
function _shift_bilinear(a::Matrix{Float64}, shift::Tuple{Real,Real})
    dx, dy = Float64(shift[1]), Float64(shift[2])
    nr, nc = size(a)
    out = similar(a)
    @inbounds for j in 1:nc, i in 1:nr
        y, x = i - dy, j - dx
        i0, j0 = floor(Int, y), floor(Int, x)
        fy, fx = y - i0, x - j0
        v = 0.0
        for (dj, wj) in ((0, 1 - fx), (1, fx)), (di, wi) in ((0, 1 - fy), (1, fy))
            w = wi * wj
            w == 0 && continue
            ii = clamp(i0 + di, 1, nr)
            jj = clamp(j0 + dj, 1, nc)
            v += w * a[ii, jj]
        end
        out[i, j] = v
    end
    return out
end

"""
    inferred_type(f, argtypes::Tuple) -> Type

The return type Julia's inference derives for `f(::argtypes...)`.

`Base.infer_return_type` would be the direct spelling, but it does not exist before Julia 1.11 and
this package supports 1.10 — using it made every `lts` CI job error rather than fail, which is how
the gap surfaced. `Base.return_types` is available on both and returns a vector of candidates, one
per matching method; these call sites all have a single method, so the sole element is the answer.
"""
function inferred_type(f, argtypes::Tuple)
    ts = Base.return_types(f, argtypes)
    length(ts) == 1 || error("expected one method for $f$(argtypes), inference gave $(length(ts))")
    return only(ts)
end
